FROM visiont3lab/ubuntu-xfce-vnc:cpu-programming

MAINTAINER Manuel Rucci "ruccimanuel7@gmail.com"

### Add all install scripts for further steps
ADD ./scripts/ $INST_SCRIPTS/
ADD ./scripts/setup/startup $STARTUPDIR
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} +

# -------- Place here the new scripts ------ #

# Install opencv
RUN $INST_SCRIPTS/lib/opencv-cpu.sh

# Install pixel annotationt tool
RUN $INST_SCRIPTS/lib/pixel_annotation_tool.sh

# ------------------------------------------ #

ENTRYPOINT ["/dockerstartup/vnc_startup.sh"]
CMD ["--wait"]
